### ISSUE TITLE
Volume Support?

### ISSUE THREAD

**Issue by itsforrest** [hensm/node-ddcci#13]
Any plans on adding support for monitor volume controls?

**Comment by hensm** [comment]
There isn't a separate method for it, but there is support for setting arbitrary VCP code values. I can't test since my monitors have no support for it, but you should be able to do this:

````js
let monitorId, level; // ...
ddcci._setVCP(monitorId, ddcci.vcp.AUDIO_SPEAKER_VOLUME, level)
````
