### ISSUE TITLE
Update package on npm

### ISSUE THREAD

**Issue by xanderfrangos** [hensm/node-ddcci#8]
Your library has been super helpful for my monitor brightness tool, but I noticed your repository and npm package are out of sync. I didn't even see commit 2d3fb14 until I had to fix issues related to identifying monitors. That commit is critical to consistently identifying unique displays and should be on npm. 

Thanks for making this library!

**Comment by hensm** [comment]
I'm glad you find it useful.

I'd be happy to publish a new version, but embarrassingly I've managed to lock myself out of my npm account (no OTP). I've submitted a support request, so I'll see what happens.

**Comment by hensm** [comment]
After eight(?) months, npm finally resolved my issue, so I can update the package now.
